test: &default

  # Credentials for REST APIs
  client_id: AYMJQHApnUhXOUWg-5_V3g8SgZ4S8_abMaDuQYlbQvIcYp2L4jaSvj69PaQox2GPR_hPr72_3jp9hP5S
  client_secret: ELJB3k_zor_hgrbN7_kHsZXVhLbTzmxJ6kNoRtyauVU3-Qhs2sUvDIZf59B82dFZ-lnaFoH6-baYXWYh
  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: Platform.sdk.seller@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
